name: Update Umami Script

on:
  schedule:
    - cron: "15 7 * * 1" # Every Monday at 7:15 AM UTC. Chile time zone is UTC-3 or UTC-4, so it's about 4:15 AM in Chile.
  workflow_dispatch: # Allows manual trigger
  push:
    paths:
      - .github/workflows/update-umami.yml

jobs:
  update-umami:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download latest umami.js
        run: |
          curl -sSL https://cloud.umami.is/script.js -o analytics.js

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add analytics.js
          git diff --cached --quiet || git commit -m "chore: update umami script"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
